# Generated by Django 3.1 on 2020-08-14 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('url_link', models.CharField(max_length=40)),
                ('date_judged', models.DateTimeField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['first_name']},
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.IntegerField()),
                ('usability', models.IntegerField()),
                ('creativity', models.IntegerField()),
                ('content', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='awards.developer')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='awards.submission')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='awards.developer'),
        ),
        migrations.AddField(
            model_name='submission',
            name='tags',
            field=models.ManyToManyField(to='awards.tags'),
        ),
    ]
