# Generated by Django 3.1 on 2020-08-14 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_developer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='submissions/'),
            preserve_default=False,
        ),
    ]
