# Generated by Django 3.1 on 2020-08-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_submission_submission_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardNewsRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
