# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-16 09:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0007_auto_20200816_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
