# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-16 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0008_auto_20200816_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardsAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('developer', models.CharField(max_length=40)),
                ('url_link', models.CharField(max_length=40)),
            ],
        ),
    ]
