# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-17 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0009_awardsapi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='date_judged',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='creativity',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='mobile',
        ),
    ]
